# Generated by Django 3.0.6 on 2020-07-16 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adapp', '0003_auto_20200716_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='tags',
        ),
        migrations.AddField(
            model_name='ad',
            name='tags',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='adapp.Tag', verbose_name='Теги'),
        ),
    ]
