# Generated by Django 3.0.6 on 2020-07-19 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adapp', '0014_auto_20200719_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='tag',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='adapp.Tag'),
        ),
    ]
